### ISSUE TITLE
how to deal with ffmpeg-python

### ISSUE THREAD

**Issue by hahakid** [hcardwell/usb-vsp#1]
Nice work. It works well on ubuntu16, but sometimes still need to reboot hardware.
I tries to get the frames through a ffmpeg wrapper and transport to numpy array for some post-process.
I tries to use output.FIFO as ffmpeg input, but not work.
And I found th FIFOWriter write something in to "/tmp/vsp-fifo".
Is there anyway that I can directly deal with the video steam (not through the ffplay )?

And if there is a more robust exit mechanism

**Comment by hcardwell** [comment]
The main reason to use ffplay is that we benefit from that project's excellent work making hardware acceleration for the decode work.  Since I had done my reverse engineering work on the DJIPlay app on Android on SBCs, my intended use-case was on little computers--even on a Raspberry Pi.

Unplugging and re-plugging the headset (it's prudent to wait about 5 seconds between those actions) should suffice for the Python script to kill all the running ffplay instances and start everything back up when the headset is detected again.  That is the clean "reset eveything" path in the player.  For sure, more maturity in some of that would be welcome, and when I have time I will probably make everything easier to use.  

On Linux, the FIFO used to me a semaphore for data to pass from the running program to the player is indeed located at /tmp/vsp-fifo.  You can also read from this FIFO using other things, like mbuffer, dd, or netcat as well to move playback somewhere else over the network.  You can treat the FIFO as a file if you want to mess with it.  The FIFOWriter class will start blocking if nothing is pulling data from the FIFO though.  But doing any of the things you're talking about will require you to do some hacking of the code in djiplayer.py.  But it is all there for the hacking, so knock yourself out.

One of the forks of my code on Github (sorry, can't look right this minute) uses the CV framework in Python to directly render the frames from Python rather than using an external player.  I do not advocate this approach since it's way more CPU-intensive.  I just use a laptop these days in the field having given up on the SBC route, but on the Raspberry Pi 4 for example even ffplay without hardware offload of the decode can't keep up with the stream from the goggles.

**Comment by hahakid** [comment]
@hcardwell Thanks for your relpy, I followed that fork and achieved my goal, I added a CNN detector at the end for realtime detection.
However, the quality of current video steam is not so well and caused a lot of errors. 
I am facing the problem of how to improve the per frame quality.

**Comment by hcardwell** [comment]
@hahakid Glad it was somewhat helpful.  What you are experiencing is why I use ffmpeg and believe it to be the better option.  But good luck with the optimization.
